apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-yolo
  labels:
    app: polybot-yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-yolo
  template:
    metadata:
      labels:
        app: polybot-yolo
    spec:
      containers:
      - name: server
        image: yaeli1/yolo5-microservice-dev:0.0.1
        ports:
        - containerPort: 3002
        env:
        - name: TELEGRAM_APP_URL
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: TELEGRAM_APP_URL
        - name: ALB_URL
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: ALB_URL
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: REGION
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: BUCKET_NAME
        - name: DYNAMODB_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: DYNAMODB_TABLE_NAME
        - name: YOLO_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: YOLO_QUEUE_NAME

        - name: CERT_PREFIX
          valueFrom:
            configMapKeyRef:
              name: yolo-config
              key: CERT_PREFIX
---
apiVersion: v1
kind: Service
metadata:
  name: polybot-yolo-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002