apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-filters
  labels:
    app: polybot-filters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-filters
  template:
    metadata:
      labels:
        app: polybot-filters
    spec:
      containers:
      - name: server
        image: yaeli1/filters-microservice-dev:0.0.1
        ports:
        - containerPort: 3001
        env:
        - name: TELEGRAM_APP_URL
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: TELEGRAM_APP_URL
        - name: ALB_URL
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: ALB_URL
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: REGION
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: BUCKET_NAME
        - name: DYNAMODB_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: DYNAMODB_TABLE_NAME
        - name: YOLO_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: YOLO_QUEUE_NAME
        - name: FILTERS_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: polybot-config
              key: FILTERS_QUEUE_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: polybot-filters-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001