version: '3.8'  # Specify the version of docker-compose

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jobs:/var/jenkins_home/jobs
      - ./nodes:/var/jenkins_home/nodes
      - jenkins_home:/var/jenkins_home
    restart: on-failure  # Consider changing to unless-stopped for more resilience
    networks:
      - jenkins-net

  agent1:
    build:
      context: .
      dockerfile: jenkins-agent.Dockerfile
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=${JENKINS_SECRET}  # Ensure JENKINS_SECRET is in your .env file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - ${DOCKER_GROUP_ID}  # Ensure DOCKER_GROUP_ID is in your .env file
    networks:
      - jenkins-net

volumes:
  jenkins_home:
networks:
  jenkins-net: