name: Cluster Initialization

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
      environment:
        required: true
        type: string
      app-url:
        required: true
        type: string
    secrets:
      TELEGRAM_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform  # The directory containing your Terraform configuration files

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the control plane ip
        run: |
          EC2_CONTROL_PLANE=$(aws ec2 describe-instances --region ${{ inputs.region-code }} \
              --filters "Name=tag:Name,Values=*control-plane*" \
                        "Name=tag:Name,Values=*yaelwil*" \
                        "Name=tag:Name,Values=*k8s-project*" \
              --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' \
              --output json)
          
          # Extract Control Plane IPs
          CONTROL_PLANE_IP=$(echo "$EC2_CONTROL_PLANE" | jq -r '.[][] | select(.[1] == "running") | .[2]')          
          INSTANCE_CP_ID=$(echo "$EC2_CONTROL_PLANE" | jq -r '.[][] | select(.[1] == "running") | .[0]')
          echo "CONTROL_PLANE_IP=$CONTROL_PLANE_IP" >> $GITHUB_ENV
          echo "INSTANCE_CP_ID=$INSTANCE_CP_ID" >> $GITHUB_ENV

      - name: Copy k8s file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > yaelwil-private-key.pem
          chmod 400 yaelwil-private-key.pem
          
          # Ensure the namespace exists
          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP \
          "kubectl create namespace ${{ inputs.environment }}" || echo 'Namespace already exists'

          cat <<EOF > polybot-${{ inputs.environment }}-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: polybot-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
            CERT_PREFIX: "yaelwil-certificate-${{ inputs.environment }}-${{ inputs.region-code }}"
          EOF

          # Generate the ConfigMap YAML file
          cat <<EOF > filters-${{ inputs.environment }}-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: filters-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
          EOF
          
          # Generate the ConfigMap YAML file
          cat <<EOF > yolo-${{ inputs.environment }}-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: yolo-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
          EOF

          # Securely copy files to the remote server
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" filters-${{ inputs.environment }}-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/FiltersMicroservice
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" polybot-${{ inputs.environment }}-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/PolybotMicroservice
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" yolo-${{ inputs.environment }}-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/YoloMicroservice

          # Clean up the private key
          rm yaelwil-private-key.pem
        env:
          CONTROL_PLANE_IP: ${{ env.CONTROL_PLANE_IP }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Create secret
        run: |
          export REGION=${{ inputs.region-code }}
          export ENV=${{ inputs.environment }}
          export CERT_PREFIX="yaelwil-certificate-${{ inputs.environment }}-${{ inputs.region-code }}"
          export KEY_PREFIX="yaelwil-certificate-pk-${{ inputs.environment }}-${{ inputs.region-code }}"
          export SECRET_NAME="tls-secret-${{ inputs.environment }}"

          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP \
          "export CERT_PREFIX=$CERT_PREFIX && export KEY_PREFIX=$KEY_PREFIX && export SECRET_NAME=$SECRET_NAME && python3 ~/k8s/PolyboInfra/k8s/ingress_setup.py"
