name: Polybot Infrastructure Terraform Environment

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
      environment:
        required: true
        type: string
      app-url:
        required: true
        type: string
    secrets:
      TELEGRAM_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform  # The directory containing your Terraform configuration files
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Terraform init
        run: terraform init

      - name: Terraform workspace select
        run: terraform workspace select ${{ inputs.region-code }}-${{ inputs.environment }} || terraform workspace new ${{ inputs.region-code }}-${{ inputs.environment }}

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: | 
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform plan -var-file=region.${{ inputs.region-code }}.${{ inputs.environment }}.tfvars

      - name: Terraform apply
        run: |
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform apply -auto-approve -var-file=region.${{ inputs.region-code }}.${{ inputs.environment }}.tfvars

      - name: Get the control plane ip
        run: |
          EC2_CONTROL_PLANE=$(aws ec2 describe-instances --region ${{ inputs.region-code }} \
              --filters "Name=tag:Name,Values=*control-plane*" \
                        "Name=tag:Name,Values=*yaelwil*" \
                        "Name=tag:Name,Values=*${{ inputs.environment }}*" \
                        "Name=tag:Name,Values=*k8s-project*" \
              --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' \
              --output json)
          
          # Extract Control Plane IPs
          CONTROL_PLANE_IP=$(echo "$EC2_CONTROL_PLANE" | jq -r '.[][] | select(.[1] == "running") | .[2]')          
          INSTANCE_CP_ID=$(echo "$EC2_CONTROL_PLANE" | jq -r '.[][] | select(.[1] == "running") | .[0]')
          echo "CONTROL_PLANE_IP=$CONTROL_PLANE_IP" >> $GITHUB_ENV
          echo "INSTANCE_CP_ID=$INSTANCE_CP_ID" >> $GITHUB_ENV

      - name: Get the worker node ip
        run: |
          EC2_WORKER_NODE=$(aws ec2 describe-instances --region ${{ inputs.region-code }} \
              --filters "Name=tag:Name,Values=*control-plane*" \
                        "Name=tag:Name,Values=*yaelwil*" \
                        "Name=tag:Name,Values=*${{ inputs.environment }}*" \
                        "Name=tag:Name,Values=*k8s-project*" \
              --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' \
              --output json)
          
          # Extract Worker Nodes IPs
          WORKER_NODE_IP=$(echo "$EC2_CONTROL_PLANE" | jq -r '.[][] | select(.[1] == "running") | .[0]')
          echo "INSTANCE_WN_IDS=$WORKER_NODE_IP" >> $GITHUB_ENV

      - name: Copy k8s file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > yaelwil-private-key.pem
          chmod 400 yaelwil-private-key.pem
          
          # Ensure the namespace exists
          ssh -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" ubuntu@$CONTROL_PLANE_IP \
          "kubectl create namespace ${{ inputs.environment }}" || echo 'Namespace already exists'"

          # Generate the ConfigMap YAML file
          cat <<EOF > polybot-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: polybot-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
            CERT_PREFIX: "yaelwil-certificate-${{ inputs.environment }}-${{ inputs.region-code }}"
          EOF
          
          # Generate the ConfigMap YAML file
          cat <<EOF > filters-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: filters-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
          EOF
          
          # Generate the ConfigMap YAML file
          cat <<EOF > yolo-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: yolo-config
            namespace: ${{ inputs.environment }}
          data:
            TELEGRAM_APP_URL: "https://${{ inputs.app-url }}"
            ALB_URL: "http://${{ inputs.app-url }}:80"
            REGION: "${{ inputs.region-code }}"
            BUCKET_NAME: "yaelwil-bucket-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            DYNAMODB_TABLE_NAME: "yaelwil-dynamodb-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project"
            YOLO_QUEUE_NAME: "yaelwil-yolov5-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
            FILTERS_QUEUE_NAME: "yaelwil-filters-sqs-queue-${{ inputs.environment }}-${{ inputs.region-code }}-k8s-project.fifo"
          EOF 

          # Securely copy files to the remote server
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" -r ../k8s ubuntu@$CONTROL_PLANE_IP:~/k8s
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" filters-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/FiltersMicroservice
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" polybot-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/PolybotMicroservice
          scp -o StrictHostKeyChecking=no -i "yaelwil-private-key.pem" yolo-configmap.yaml ubuntu@$CONTROL_PLANE_IP:~/k8s/YoloMicroservice

          # Clean up the private key
          rm yaelwil-private-key.pem
        env:
          CONTROL_PLANE_IP: ${{ env.CONTROL_PLANE_IP }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}