name: Polybot Destroy Terraform Environment

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Infrastructure destroying
        if: ${{ github.event.inputs[ matrix.region ] == 'true' }}
        working-directory: terraform
        run: |
          # init terraform 
          terraform init
          
          # select workspace or create if needed
          terraform workspace select ${{ inputs.region-code }}-${{ inputs.environment }}  || terraform workspace new ${{ inputs.region-code }}-${{ inputs.environment }}

          # tf destroy 
          terraform destroy -auto-approve -var-file=${{ inputs.region-code }}.${{ inputs.environment }}.tfvars