name: Polybot Main

on:
  workflow_dispatch:
    inputs:
      Build_Development_eu_west_1:
        description: 'Build Development (eu-west-1)'
        required: false
        type: boolean
      Build_Production_eu_west_1:
        description: 'Build Production (eu-west-1)'
        required: false
        type: boolean
      Build_Production_us_east_2:
        description: 'Build Production (us-east-2)'
        required: false
        type: boolean
      Initialize_Cluster_eu_west_1:
        description: 'Initialize Cluster (eu-west-1)'
        required: false
        type: boolean
      Initialize_Cluster_us_east_2:
        description: 'Initialize Cluster (us-east-2)'
        required: false
        type: boolean
      Destroy_Development_eu_west_1:
        description: 'Destroy Development (eu-west-1)'
        required: false
        type: boolean
      Destroy_Production_eu_west_1:
        description: 'Destroy Production (eu-west-1)'
        required: false
        type: boolean
      Destroy_Production_us_east_2:
        description: 'Destroy Production (us-east-2)'
        required: false
        type: boolean

jobs:
  Build_Development_eu_west_1:
    if: ${{ github.event.inputs.Build_Development_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-environment.yaml
    with:
      region-code: eu-west-1
      environment: dev
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_DEV }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}

  Build_Production_eu_west_1:
    if: ${{ github.event.inputs.Build_Production_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-environment.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_PROD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}

  Build_Production_us_east_2:
    if: ${{ github.event.inputs.Build_Production_us_east_2 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-environment.yaml
    with:
      region-code: us-east-2
      environment: prod
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_PROD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_US_EAST_2_K8S }}


  Destroy_Development_eu_west_1:
    if: ${{ github.event.inputs.Destroy_Development_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-destroy-environment.yaml
    with:
      region-code: eu-west-1
      environment: dev
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Destroy_Production_eu_west_1:
    if: ${{ github.event.inputs.Destroy_Production_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-destroy-environment.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Destroy_Production_us_east_2:
    if: ${{ github.event.inputs.Destroy_Production_us_east_2 == 'true' }}
    uses: ./.github/workflows/infra-destroy-environment.yaml
    with:
      region-code: us-east-2
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
  Initialize_Cluster_eu_west_1:
    if: ${{ github.event.inputs.Initialize_Cluster_eu_west_1 == 'true' }}
    uses: ./.github/workflows/k8s-cluster-initialization.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Initialize_Cluster_us_east_2:
    if: ${{ github.event.inputs.Initialize_Cluster_us_east_2 == 'true' }}
    uses: ./.github/workflows/k8s-cluster-initialization.yaml
    with:
      region-code: us-east-2
      environment: prod
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_PROD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_US_EAST_2_K8S }}