name: Polybot Main

on:
  workflow_dispatch:
    inputs:
      Build_eu_west_1:
        description: 'Build eu-west-1'
        required: false
        type: boolean

      Destroy_eu_west_1:
        description: 'Destroy eu_west_1'
        required: false
        type: boolean
jobs:
  Build_eu_west_1:
    if: ${{ github.event.inputs.Build_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-west-1
      telegram_app_url_dev: yaelwil-dev.int-devops.click
      telegram_app_url_prod: yaelwil.int-devops.click
    secrets:
      TELEGRAM_TOKEN_DEV: ${{ secrets.TELEGRAM_TOKEN_DEV }}
      TELEGRAM_TOKEN_PROD: ${{ secrets.TELEGRAM_TOKEN_PROD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}

  Destroy_eu_west_1:
    if: ${{ github.event.inputs.Destroy_eu_west_1 == 'true' }}
    uses: ./.github/workflows/infra-destroy-region.yaml
    with:
      region-code: eu-west-1
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}