name: Polybot Main

on:
  workflow_dispatch:
    inputs:
      Build_Development:
        description: 'Build Development (eu-west-1)'
        required: false
        type: boolean
      Build_Production:
        description: 'Build Production (eu-west-1)'
        required: false
        type: boolean
      Initialize_cluster_Development:
        description: 'Initialize cluster Development (eu-west-1)'
        required: false
        type: boolean
      Initialize_cluster_Production:
        description: 'Initialize cluster Production (eu-west-1)'
        required: false
        type: boolean
      Destroy_Development:
        description: 'Destroy Development (eu-west-1)'
        required: false
        type: boolean
      Destroy_Production:
        description: 'Destroy Production (eu-west-1)'
        required: false
        type: boolean


jobs:
  Build_Development:
    if: ${{ github.event.inputs.Build_Development == 'true' }}
    uses: ./.github/workflows/infra-provisioning-environment.yaml
    with:
      region-code: eu-west-1
      environment: dev
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_DEV }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}


  Build_Production:
    if: ${{ github.event.inputs.Build_Production == 'true' }}
    uses: ./.github/workflows/infra-provisioning-environment.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_PROD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}

  Destroy_Development:
    if: ${{ github.event.inputs.Destroy_Development == 'true' }}
    uses: ./.github/workflows/infra-destroy-environment.yaml
    with:
      region-code: eu-west-1
      environment: dev
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Destroy_Production:
    if: ${{ github.event.inputs.Destroy_Production == 'true' }}
    uses: ./.github/workflows/infra-destroy-environment.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Initialize_cluster_Development:
    if: ${{ github.event.inputs.Initialize_cluster_Development == 'true' }}
    uses: ./.github/workflows/k8s-cluster-initialization.yaml
    with:
      region-code: eu-west-1
      environment: dev
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  Initialize_cluster_Production:
    if: ${{ github.event.inputs.Initialize_cluster_Production == 'true' }}
    uses: ./.github/workflows/k8s-cluster-initialization.yaml
    with:
      region-code: eu-west-1
      environment: prod
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_K8S }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

